# Generated by Django 4.1.2 on 2023-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='uuid',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
