# Generated by Django 4.1.2 on 2023-04-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_shortenurl_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='full_url',
            field=models.URLField(max_length=250),
        ),
    ]
